vagrantfile:
    target: local
    vm:
        provider:
            local:
                #nom de la maquina
                box: vagrant_xavi
                # adreça del paquet
                box_url: file:///C:/Users/ClickDo/VirtualBox%20VMs/package.box
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 1
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_m1b4s3kso32o:
                        id: daw
                        network:
                            private_network: 192.168.56.60
                            forwarded_port:
                                vflmnfp_blkhtta9q760:
                                    host: '5794'
                                    guest: '22'
                        hostname: vagrant
                        memory: '4096'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_9f3pm5dtamaw:
                source: 'c:/xampp/htdocs'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_45i04dzgrc08:
                source: ''
                target: ''
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
    # GUI Desktop Tools
        # ubuntu trusty official packages
        - lxde # LX Desktop Environment
        - gdm # Gnome Desktop Environment
        - alacarte  # menu editor
        - gdebi     # package installer
        - libreoffice # office suite
        - retext    # markdown editor

    # gui browsers
        - chromium-browser
        - firefox

    # non-gui browsers and downloaders
        # ubuntu trusty official packages
        - curl
        - wget
        - lynx

    # Server Admin Tools
        # brought by webmin ppa
        # key added with `wget -O - http://www.webmin.com/jcameron-key.asc | sudo apt-key add -`
        # @see http://www.unixmen.com/install-webmin-ubuntu-14-04/
            # "webmin.list" source file placed under /etc/apt/sources.list.d/ folder
        - webmin
        # ubuntu trusty official packages
        - nagios3


    # DBMS Admin tools (SGBD Adminstración)
        # brought by mysql ppa
        # key added with `sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5072E1F5`
        # @see http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup
        # @see http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-available
            # "mysql.list" source file placed under /etc/apt/sources.list.d/ folder
        - mysql-workbench-community

        # ubuntu trusty official packages
        - pgadmin3 # gui postgres administration tool
        - wine # windows emulator, necessary to run HeidiSQL
        - phpmyadmin # web interface mysql adminstration tool

    # DBMS Management tools (less than Admin)
        # DBeaver downloaded from jkiss.org
        # installed with `wget -O /tmp/dbeaver.deb http://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb; sudo dpkg -i /tmp/dbeaver.deb; sudo apt-get install -f`
        #- dbeaver

    # CASE Tools
        # brought by bouml ppa
        # key added with `wget -O - http://www.bouml.fr/bouml_key.asc | sudo apt-key add -`
        # @see http://www.bouml.fr/download.html
            # "bouml.list" source file placed under /etc/apt/sources.list.d/ folder
        - bouml
        # Old release, available at http://old-releases.ubuntu.com/ubuntu/pool/main/x/xft/libxft-dev_2.1.2-6_amd64.deb
        # - libxft-dev # used by DBDesigner 4

    # IDEs
        # brought by sublime ppa
        # ppa added with `sudo add-apt-repository ppa:webupd8team/sublime-text-3`
        - sublime-text

        # ubuntu trusty official packages
        - eclipse
    # CVS
        # ubuntu trusty official packages
        - git

    # System binaries and libraries
        - nano
        - git
        - php5-xdebug
        - ssh
        - nagios3
        - curl
        - libreoffice
        - chromium-browser
        - firefox
        - cron
        - php5-redis
        - uuid
        - openssl
        - libyaml-0-2
        - libghc-base64-conduit-dev
        - squid3
        - php5-mysql
        - php5-dev
users_groups:
    install: '1'
    groups: {  }
    users:
        - 'daw:www-data:sudo:users:vagrant:cdrom'
locale:
    install: '1'
    settings:
        default_locale: es_ES.UTF-8
        locales:
            - ca_ES.UTF-8
            - en_GB.UTF-8
            - en_US.UTF-8
            - es_ES.UTF-8
        timezone: Etc/GMT+1
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_c8vxtfzd05sb:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_2n4xwaeg3ez1:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_q94d53hm5gmz:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - expires
        - headers
        - info
        - mime_magic
        - proxy_fcgi
        - rewrite
        - userdir
        - vhost_alias
    vhosts:
        av_09x1fdsk9w1i:
            servername: bazaary.local
            docroot: /var/www/bazaary/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_2sqjwyhb27pa:
                    path: /var/www/bazaary/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_hvqtytvmfup2:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory

        bazaary.master:
            servername: bazaary.master
            docroot: /var/www/bazaary-master/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_2sqjwyhb27pa:
                    path: /var/www/bazaary-master/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_hvqtytvmfup2:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - curl
            - imagick
            - xmlrpc
            - xsl
            - dbg
            - mysqlnd
            - sqlite
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php.log
        # log_level: debug
    fpm_pools:
        phpfp_gz2f80s5dzc1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '0'
        xdebug.remote_enable: '1'
        xdebug.remote_host: 127.0.0.1
        xdebug.remote_handler: dbgp
        xdebug.remote_port: 9001
        xdebug.remote_mode: req
        xdebug.remote_log: '/var/log/xdebug.log'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_16y6p0r8i8gm:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_uzqv2uvgoujl:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_8eoqqzbf8dyt:
            name: dbname
            sql: ''
    grants:
        mariadbng_clj9obrixvjs:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '1234'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_6ti4u0x3kaz0:
            name: bazaary
            password: '1234'
    databases:
        mysqlnd_840wt0hy5dq7:
            name: bazaary
            sql: ''
    grants:
        mysqlng_lvymmen0gsx2:
            user: bazaary
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '1234'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: '1'
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: '1'
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_jcwmvz4pg03e:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

